services:
  mcp-server:
    build:
      context: ./mcp_server
    ports:
      - "8000:8000"
    networks:
      - app-network

  mcp-inspector:
    build:
      context: ./inspector
    ports:
      - "6274:6274"
      - "6277:6277"
    environment:
      - HOST=0.0.0.0
      - DANGEROUSLY_OMIT_AUTH=true
    networks:
      - app-network
    depends_on:
      - mcp-server

networks:
  app-network:
    driver: bridge