[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "polars>=1.32.3",
    "restrictedpython>=8.0",
]

[dependency-groups]
dev = [
    "pyclean>=3.1.0",
]
